language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
mono:
  - weekly
os:
  - linux
  - osx
osx_image: xcode7.1
matrix:
  allow_failures:
    - os: osx
script:
  - ./build.sh verify
notifications:
  email:
    on_failure: change
